module.exports = {
    EMAIL_NOT_PROVIDED: "Email not provided",
    EMAIL_NOT_FOUND: "Email not found",
    EMAIL_INVALID_FORMAT: "Email in invalid format",
    EMAIL_TAKEN: "User with specified email already exists",
    NAME_NOT_PROVIDED: "Name not provided",
    SURNAME_NOT_PROVIDED: "Surname not provided",
    DEPARTMENT_NOT_PROVIDED: "Department not provided",
    DEPARTMENT_NOT_FOUND: "Department not found",
    SALARY_NOT_PROVIDED: "Salary not provided",
    SALARY_NOT_NUMBER: "Salary must be a number",
    SALARY_NOT_POSITIVE: "Salary must be a positive number",
    STACK_NOT_PROVIDED: "Stack not provided",
    PASSWORDS_DO_NOT_MATCH: "Passwords do not match",
    PASSWORD_NOT_PROVIDED: "Password not provided",
    INCORRECT_PASSWORD: "Incorrect password",
    FAILED_TO_SEND_EMAIL: "Failed to send email",
    USER_ROLE_NOT_FOUND: "User role not found",
    USER_NOT_FOUND: "User not found",
    ID_NOT_PROVIDED: "ID not provided",
    ID_WRONG_FORMAT: "ID is in wrong format",
    PASSWORD_TOKEN_EXPIRED: "The password reset token has expired",
    INVALID_TOKEN: "Token is not valid",
    TOKEN_EXPIRED: "The Token has expired",
    PROJECT_NOT_FOUND: "Project not found",
    INVALID_PROJECT_ID: "Invalid project id",
    DATA_NOT_FOUND: "Data not found",
    PAGE_NUMBER_LESS_THAN_1: "Page number must be greater than 0",
    PAGE_SIZE_LESS_THAN_0: "Page size must be greater than 0",
    PAGE_SIZE_NOT_PROVIDED: "Page size not provided",
    FAILED_TO_CREATE_EMPLOYEE: "Failed to create employee",
    EMPLOYEE_NOT_FOUND: "Employee not found",
    FAILED_TO_GET_EMPLOYEE: "Failed to get employee",
    FAILED_TO_GET_EMPLOYEES: "Failed to get employees",
    FAILED_TO_UPDATE_EMPLOYEE: "Failed to update employee",
    FAILED_TO_DELETE_EMPLOYEE: "Failed to delete employee",
    FAILED_TO_GET_EMPLOYEES: "Failed to get employees",
    FAILED_TO_UPDATE_PROJECT: "Failed to update project",
    FAILED_TO_DELETE_PROJECT: "Failed to delete project"

  };
  